title: Hwanhui Jo
description: 
site_title: 'Hwanhui Jo'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: Hwanhuii
blog_url: https://www.nagekar.com
email: wh020627@gmail.com
keybase_username: abhn
twitter_username: abhn_
reddit_username: abhn

# absolute or relative
profile_picture: assets/images/me.png

# Google Analytics ID
google_analytics: 