title: Hwanhui Jo
description: 
site_title: 'Hwanhui Jo'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: Hwanhuii
blog_url: 
email: wh020627@gmail.com
keybase_username: 
twitter_username: 
reddit_username: 

# absolute or relative
profile_picture: assets/images/personal.jpg

# Google Analytics ID
google_analytics: 